#!\/bin\/bash
Universe     = vanilla
Notification = Complete
Executable   = /uscms/home/javiert/work/CMSSW_5_2_5/src/SusyAnalysis/LostLepton/test/cmsRunScript.sh
Arguments    = bgList$(Process) BGout/outCondorProc$(Process)
Should_Transfer_Files = YES
WhenTOTransferOutput  = ON_EXIT
Output       = log/bg$(Process).stdout
Error        = log/bg$(Process).stderr
Log          = log/bg$(Process).condorlog
notify_user  = javiert@FNAL.GOV
Queue 50
